### ISSUE TITLE
Windows builds copy all the test*.exe files into %LIBRARY_BIN%

### ISSUE THREAD

**Issue by patricksnape** [conda-forge/libxml2-feedstock#18]
We should probably not ship those.

**Comment by ocefpaf** [comment]
In terms to reduce package space or b/c they may be harmful in some way? I can do it but depending on your answer it may take a while :smile:

**Comment by patricksnape** [comment]
Merely because they are polluting the bin folder and they don't have particularly unique names so they increase the probability of collision!

**Comment by ocefpaf** [comment]
So harmful and we need to deal with this ASAP. I will take a look at doing this later today.

Thanks @patricksnape!
