### ISSUE TITLE
ICU is too big and linked to too many things (sometimes statically).

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/libxml2-feedstock#41]
Linking ICU to libxml2 makes libxml2 go from a small dependency to a heavy one. Examples of things that end up needing it are libarchive, libxar (clang compilers) and more.

I'd like to propose making a new package, `libxml2-noicu` that doesn't link to ICU and using that in packages where ICU is deemed too heavy a dependency. My future plans necessitate doing this for `AD` but it would be great to remain in-sync with conda-forge on this.

**Comment by mingwandroid** [comment]
That sounds fine to me @ocefpaf, both the meeting and/or your opposite proposal.

**Comment by mingwandroid** [comment]
I do have a slight preference for the canonically named package to be as 'fully-featured' as we can make it but I'm not militant about that at all, particularly in this case since I don't believe (not having checked, happy to be wrong) that linking ICU to libxml2 is a common practice.

**Comment by jakirkham** [comment]
What if we made `icu` a `run_constrained` dependency? Maybe that would be the best of both worlds.

**Comment by jakirkham** [comment]
Should add I think part of the reason `icu` got added was there were some build issues on macOS if it wasn't included. Though things have evolved so much since and my memory is a bit hazy on the details. It's probably worth re-exploring this.

**Comment by mingwandroid** [comment]
We *could* contemplate linking to the macOS system `libicu` here too (and perhaps in some other cases?). It's a bit of a travesty to even suggest this I know! We'd need to be careful about compatibility and link to macOS 10.9's ideally. We'd also risk losing whatever codepoints were added since but I believe it'd probably be fine as it'd just use the one from the end-users system and that should allow all the codepoints to be used.

**Comment by mingwandroid** [comment]
(because no end user with a choice is still running 10.9)

**Comment by mingwandroid** [comment]
> What if we made icu a run_constrained dependency? Maybe that would be the best of both worlds

libxml2 would just fail to load. You would need to patch it to use runtime library detection and loading `dl_load` for ICU and that'd be a big undertaking I reckon.

**Comment by ocefpaf** [comment]
This one is back to haunt me. It turns out this is the main blocker for folks who wants to use conda-forge packages as a source for the dependencies when building wheels. Where sometimes the size of icu alone is >90% of the final wheel.

@isuruf recommended a libxml2 variant with icu if icu is present in the environment but without it if it is not.
@conda-forge/core I'm not sure what are the implications here, a migrator if the symbols for libxml2 changes, or maybe just the variant would do? Anyone has any concerns? Should we try to tackle this 6 years old issue?

**Comment by jaimergp** [comment]
xref notes from today in https://github.com/conda-forge/conda-forge.github.io/pull/2201

**Comment by ocefpaf** [comment]
Fixed in #121.
