### ISSUE TITLE
Remove shared documentation from build

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/libxml2-feedstock#57]
Current builds seem to include 6.6MB/9.2MB of documentation.

![image](https://user-images.githubusercontent.com/90008/114323115-c3efca80-9af1-11eb-86a3-15688b81db6e.png)

It would be desirable to me if these domestication files were omitted.

Thoughts?

**Comment by ocefpaf** [comment]
Yes. Ideally we should create a split package but not sure it is worth it. Docs are all "googleable" nowadays.
