### ISSUE TITLE
Document why package was marked as broken

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/libxml2-feedstock#80]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Previously I was able to install `libxml2-2.9.12-h885dcf4_1` however it seems marked as broken now (https://anaconda.org/conda-forge/libxml2/files?page=2).

Can anyone comment on why it is marked as such?

**Comment by basnijholt** [comment]
I found the corresponding PR that marked it as broken: https://github.com/conda-forge/admin-requests/pull/514.

**Comment by jakirkham** [comment]
Packages are marked broken by PRs to [admin-requests]( https://github.com/conda-forge/admin-requests ). Generally would search there for more context.

In particular am seeing PR ( https://github.com/conda-forge/admin-requests/pull/514 ) marked some `libxml2` packages as broken recently. Maybe this includes the package of interest?

That PR in turn is referenced by issue ( https://github.com/conda-forge/lxml-feedstock/issues/75 ).
